story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('books/', include('story8.urls')),
    path('', include('story9.urls')),
]

story6/urls.py
from django.urls import path
from .views import *

app_name = 'story6'

urlpatterns = [
    path('status/', index, name='index'),
    path('add_status/', add_status, name='add_status'),
]

story7/urls.py
from django.urls import path
from .views import *

app_name = 'story7'

urlpatterns = [
    path('', profile, name='profile'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.books, name='books'),
    path('getJson/<str:query>/', views.getJson, name='getJson'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('login/', views.loginView, name='loginView'),
    path('logout/', views.logoutView, name='logoutView'),
    path('registered/', views.registered, name='registered'),
]

story6/models.py
from django.db import models
import datetime

# Create your models here.
class Status(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	status = models.TextField(max_length=300)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django import forms
from .models import Status
from django.forms import ModelForm

class StatusForm(ModelForm):
	class Meta:
		model = Status
		fields = ['status']
		labels = {'status' : 'Status'}
		widgets = {
			'status' : forms.Textarea(attrs={
                'class': 'form-control',
				'type' : 'text',
				'placeholder' : 'Tulis perasaanmu saat ini di sini :)'}),
		}

story6/views.py
from django.shortcuts import render, redirect
from .forms import StatusForm
from .models import Status
from datetime import datetime, date

# Create your views here.
def index(request):
    data = Status.objects.all()
    form = StatusForm()

    content = {
        'title' :   'Status',
        'form'  :   form,
        'text'  :   'Halo, apa kabar?',
        'data'  :   data
    }
    return render(request, 'landingpage.html', content)

def add_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
    return redirect('story6:index')

story7/views.py
from django.shortcuts import render, redirect

# Create your views here.
def profile(request):
    return render(request, 'myprofile.html')

story8/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import requests

response = {}
BOOKS_API = 'https://www.googleapis.com/books/v1/volumes?q='

# Create your views here.
def getJson(request, query):
	url = BOOKS_API + query
	json_data = json.loads(requests.get(url).text)
	return JsonResponse(json_data)

def books(request):
    return render(request, 'books.html', response)

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User

from story7.views import *

# Create your views here.

def registered(request):
    template_name = 'registered.html'
    if request.method == "POST":
        if len(request.POST) == 3:
            username_login = request.POST['username']
            password_login = request.POST['password']
                    
            user = authenticate(request, username=username_login, password=password_login)

            if user is not None:
                login(request, user)
                return redirect('story7:profile')
            else:
                return redirect('story9:registered')

    return render(request, template_name)

def loginView(request):
    if request.method == "POST":
        if len(request.POST) == 3:
            username_login = request.POST['username']
            password_login = request.POST['password']
                    
            user = authenticate(request, username=username_login, password=password_login)

            if user is not None:
                login(request, user)
                return redirect('story7:profile')
            else:
                return redirect('story9:loginView')


        elif len(request.POST) == 6:
            firstname_login = request.POST['first-name']
            lastname_login = request.POST['last-name']
            username_login = request.POST['username']
            email_login = request.POST['email']
            password_login = request.POST['password']

            users = User.objects.all()

            for user in users:
                if user.username == username_login :
                    return redirect('story9:registered')

            user = User.objects.create_user(first_name=firstname_login, last_name=lastname_login, username=username_login, email=email_login, password=password_login)
            return redirect('story9:registered')

    return render(request, 'login.html')

def logoutView(request):
    if request.method == "POST":
        logout(request)
        return redirect('story7:profile')

    return render(request, 'logout.html')

story6/templates/landingpage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Status{% endblock %}

{% block styles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

{% endblock %}


{% block content %}
<div class="tanya-kabar">
    <div class="row">
            <div class="col-md-12">
                <h1 id="hello" style="margin-top: 5%">{{ text }}</h1>
                <form id="form" style="width: 75%; margin: 0 auto" method="POST" action="{% url 'story6:add_status' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="status">
                            <strong>{{ form.status.label_tag }}</strong>
                        </label>
                        {{ form.status }}
                    </div>
                    
                    <button id="submit" type="submit" class="btn btn-light" style="font-family: Poppins-SemiBold; background-color: #CB9A7C; color: white; float: right; margin-bottom: 12.5%" value="Save">Add</button>
                </form>
            </div>
        </div>
</div>

<div class="data-kabar">
    <div class="row">
        <div class="col-md-12">
            {% if data %}
            <h1>Kumpulan perasaan dan curhatan</h1>

            <div class="row" style="margin-left: 5%; margin-right: 5%">
                {% for list in data %}
                <div id="curhatan" class="col-xs-12 col-sm-11 col-md-11 col-lg-2 col-xl-2" style="background-color: #FFF1E6; border-radius: 15px; padding: 15px; margin: 1.5%; box-shadow: 10px 10px 5px grey;">
                    <p><strong>{{ list.date }}</strong></p>
                    <p>{{ list.status }}</p>
                </div>
                {% endfor %}
            </div>

            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}

<script src="{% static 'js/script.js' %}"></script>

{% endblock %}

story7/templates/myprofile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}❀ Welcome | Inez Amandha ❀{% endblock %}

{% block styles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

{% endblock %}

{% block content %}
<div class="hello-page">
    <div class="row" style="width: 100%; height: 100%">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h1> ✿ hello! i'm inez ✿ </h1>
            <h2 style="margin-top: 2.5%"> ~ a computer science undergraduate student ~</h2>
            <h2> & </h2>
            <h2 style="margin-bottom: 50vh"> ~ an aesthetic seeker ~ </h2> 
        </div>
    </div>
</div>

<div class="about-me">
    <div class="about-me-text">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <h1> about me </h1>
            </div>
        </div>
    </div>

    <div class="about-me-content">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-4">
                <img id="profile-photo" src="{% static 'images/profile-photo.jpg' %}" style="margin: 7.5%">
            </div>
    
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-3">
                <p style="margin: 5% 2.5%">Inez Amandha (18) is a Computer Science Undergraduate Student at Faculty of Computer Science, Universitas Indonesia.
                    <br><br>
                    Inez loves to travel and go to the aesthetic places. While travelling, she will take some photos (food & places) and share her reviews on social media.
                    <br><br>
                    Currently, she is still learning how to make a website.
                    <br><br>
                    💻 And this is her second website! 💻
                    <br><br>
                    Go to main website:
                    <br>
                    <a href="https://inezamandha.herokuapp.com/" style="font-family: Poppins-Light; font-size: 16px; color: black">inezamandha.herokuapp.com</a>
                </p>
            </div>
    
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-5">
                <ul class="short-info-box">
                    <li>
                        <h2>my short info</h2>
                    </li>
                    <li>
                        <label>Name</label>
                        <span>Inez Amandha Suci</span>
                    </li>
                    <li>
                        <label>Age</label>
                        <span>18</span>
                    </li>
                    <li>
                        <label>Birthdate</label>
                        <span>December 21, 2000</span>
                    </li>
                    <li>
                        <label>Address</label>
                        <span>Depok, West Java, Indonesia</span>
                    </li>
                    <li>
                        <label>Education</label>
                        <span>University of Indonesia</span>
                    </li>
                    <li>
                        <label>Major</label>
                        <span>Computer Science (Class of 2018)</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    
</div>

<div class="resume">
    <div class="resume-text">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <h1> resume </h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <button class="accordion"><span>&#10022;</span> Activities <span>&#10022;</span></button>
            <div class="panel">
                <p style="margin-top: 1.5%;"><span>&#9998;</span> <strong>Me in Term 3: </strong></p>
                <p>Bangun Tidur <span>&#8594;</span> Kuliah <span>&#8594;</span> Rapat <span>&#8594;</span> Tidur <span>&#8594;</span> Repeat</p>
                <p><strong>#Notes</strong></p>
                <p>Nugas berada di sela-sela waktu kosong dari semua itu</p>
                <br>
                <p><span>&#9998;</span> <strong>Me on weekend: </strong></p>
                <p style="margin-bottom: 1.5%;">Masih nugas + jalan-jalan (harus disempetin! hehe)</p>
            </div>
            
            <button class="accordion"><span>&#10022;</span> Educations <span>&#10022;</span></button>
            <div class="panel">
                <p style="margin-top: 1.5%;"><span>&#9998;</span> <strong>Universitas Indonesia</strong> (2018 - sekarang) </p>
                <p>Fakultas Ilmu Komputer</p>
                <br>
                <p><span>&#9998;</span> <strong>SMAN 34 Jakarta</strong> (2015 - 2018) </p>
                <p>Jurusan IPA</p>
                <br>
                <p><span>&#9998;</span> <strong>SMPN 85 Jakarta</strong> (2012 - 2015) </p>
                <br>
                <p><span>&#9998;</span> <strong>SDN Pondok Labu 11 Pagi</strong> (2009 - 2012) </p>
                <br>
                <p><span>&#9998;</span> <strong>SDN Pondok Labu 05 Pagi</strong> (2006 - 2009) </p>
                <br>
                <p style="margin-bottom: 1.5%;"><span>&#9998;</span> <strong>TK Pertiwi VI DDN Pondok Labu</strong> (2004 - 2006) </p>
            </div>

            <button class="accordion"><span>&#10022;</span> Experiences <span>&#10022;</span></button>
            <div class="panel">
                <p style="margin-top: 1.5%"><span>&#9998;</span> <strong>BEM Fasilkom UI</strong> (2019 - sekarang) </p>
                <p>Staf Departemen Keilmuan</p>
                <br>
                <p><span>&#9998;</span> <strong>COMPFEST 11</strong> (2019) </p>
                <p>Staf Divisi Startup Academy</p>
                <br>
                <p><span>&#9998;</span> <strong>Wisuda Fasilkom UI</strong> (2019) </p>
                <p style="text-decoration: underline;"><strong>Wisuda Genap</strong></p>
                <p>PJ Divisi Konsumsi</p>
                <p style="text-decoration: underline;"><strong>Wisuda Ganjil</strong></p>
                <p>Staf Divisi Konsumsi</p> 
                <br>
                <p><span>&#9998;</span> <strong>BETIS 2019</strong> (2019) </p>
                <p>Staf Divisi Dana Usaha & Konsumsi</p>
                <br>
                <p><span>&#9998;</span> <strong>Social Project 2018</strong> (2018) </p>
                <p>Staf Divisi Dana Usaha & Konsumsi</p>
                <br>
                <p><span>&#9998;</span> <strong>High School Celebration</strong> (2016 - 2017) </p>
                <p>Staf Divisi Sponsorship</p>
                <br>
                <p><span>&#9998;</span> <strong>MPK SMAN 34 Jakarta</strong> (2015 - 2017) </p>
                <p style="text-decoration: underline;"><strong>2016 - 2017</strong></p>
                <p>Staf Komisi F (Kualitas Jasmani, Kesehatan, dan Gizi)</p>
                <p style="text-decoration: underline;"><strong>2015 - 2016</strong></p>
                <p style="margin-bottom: 1.5%">Wakil Humas</p>
            </div>
            
            <button class="accordion"><span>&#10022;</span> Achievements <span>&#10022;</span></button>
            <div class="panel">
                <p style="margin-top: 1.5%"><span>&#9998;</span> <strong>Berhasil membuat website!</strong> (2019) </p>
                <br>
                <p><span>&#9998;</span> <strong>Lomba Tari Saman Pangudi Luhur Cup 2013</strong> (2013) </p>
                <p>Juara 1</p>
                <br>
                <p><span>&#9998;</span> <strong>Lomba Menyanyi Tingkat TK se-Pondok Labu</strong> (2005) </p>
                <p>Juara 2</p>
                <br>
                <p><span>&#9998;</span> <strong>Lomba Mewarnai Tingkat TK se-Pondok Labu</strong> (2005) </p>
                <p style="margin-bottom: 1.5%">Juara 1</p>
            </div>
        </div>
    </div>
</div>

<div class="contact">
    <div class="contact-text">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <h1> contact </h1>
            </div>
        </div>
    </div>

    <div class="contact-content">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <h2>Hey, there! Let's connect! ❤ </p> 
            </div>
        </div>
    
        <div class="row">
            <div id="kotak-kontak" style="width: 350px; margin: auto 2.5% 2.5% 2.5%;">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-4">
                    <p><strong>E-mail :</strong></p>
                    <p>inezamandhasuci@gmail.com</p>
                    <p><strong>Main Website :</strong></p>
                    <a href="https://inezamandha.herokuapp.com/">inezamandha.herokuapp.com</a>
                </div>
            </div>
    
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-4">
                <div id="logo-circle">
                    <a href="https://www.instagram.com/inezamandha/">
                        <img src="{% static 'images/logo-instagram.png' %}" style="width: 55px; height: 55px; margin-top: 12.5%;">
                    </a>
                </div>
                <a href="https://www.instagram.com/inezamandha/" style="color: black;">
                    <h4 style=" display: inline-block;">Instagram</h4>
                </a>
            
                <div id="logo-circle">
                    <a href="https://twitter.com/inezamandha">
                        <img src="{% static 'images/logo-twitter.png' %}" style="width: 55px; height: 55px; margin-top: 12.5%;">
                    </a>
                </div>
                <a href="https://twitter.com/inezamandha" style="color: black;">
                    <h4 style=" display: inline-block;">Twitter</h4>
                </a>
            </div>
    
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-4">      
                <div id="logo-circle">
                    <a href="https://id.pinterest.com/inezamandha/">
                        <img src="{% static 'images/logo-pinterest.png' %}" style="width: 55px; height: 55px; margin-top: 12.5%;">
                    </a>
                </div>
                <a href="https://id.pinterest.com/inezamandha/" style="color: black;">
                    <h4 style=" display: inline-block;">Pinterest</h4>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script src="{% static 'js/script.js' %}"></script>

{% endblock %}

story8/templates/books.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Books{% endblock %}

{% block styles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/books.css' %}">

{% endblock %}

{% block content %}

<div class="cari-buku">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h1 id="cari-buku-title">Books</h1>
            <div class ="main-form" style="width: 50%; margin: 0 auto">
    
                <div class="form-group">
                    <input id='search-box' class="form-control" type="text" placeholder="Search for books name or author here">
                </div>
                <div class="form-group">
                    <button id="search-button" name="search-button" class="status-button save btn btn-light center"
                    style="font-family: Poppins-SemiBold; background-color: #CB9A7C; color: white; float: right; margin: 0 auto 20% auto"
                    >Search</button>
                </div>

            </div>
        </div>
    </div>
</div>

<div id="hasil-pencarian" style="background-color: #F2ECB6; height: 85vh; width: 100%; overflow: scroll">
    <div class='table-responsive'>
        <table class="table table-fixed">
            <thead class="text-center" style="background-color: #A96F44; color: #F7EEE5; font-family: Poppins-SemiBold">
                <tr>
                    <th scope="col" width="2.5%">No.</th>
                    <th scope="col" width="22.5%">Cover</th>
                    <th scope="col" width="22.5%">Title</th>	
                    <th scope="col" width="15%">Authors</th>
                    <th scope="col" width="15%">Publisher</th>
                    <th scope="col" width="15%">Published Date</th>
                    <th scope="col" width="10%">Details</th>
                </tr>
            </thead>
            <tbody id="books-body" class="text-center" style="font-family: Poppins-Light; background-color: #F2ECB6;">
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/books.js' %}"></script>

{% endblock %}

story9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login and Sign Up{% endblock %}

{% block styles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login_signup.css' %}">

{% endblock %}

{% block content %}

<div class="container" id="container">
	<div class="form-container sign-up-container">
		<form method="POST" action="#">
            {% csrf_token %}
            <h1>Create Account</h1>
            <div class="form-row" style="margin-top: 15px">
                <div class="col">
                    <input type="text" name="first-name" id="first-name_login" class="form-control" placeholder="First name">
                </div>
                <div class="col">
                    <input type="text" name="last-name" id="last-name_login" class="form-control" placeholder="Last name">
                </div>
            </div>
            <input type="text" name="username" id="username_login" placeholder="Username" />
			<input type="email" name="email" id="email_login" placeholder="Email" />
			<input type="password" name="password" id="password_login" placeholder="Password" style="margin-bottom: 20px" />
            <button type="submit" id="submit_login">Sign Up</button>
		</form>
	</div>
	<div class="form-container sign-in-container">
		<form method="POST" action="#">
            {% csrf_token %}
            
            <h1>Sign in</h1>
            <input type="text" name="username" id="username_login" placeholder="Username" style="margin-top: 35px" />
			<input type="password" name="password" id="password_login" placeholder="Password" style="margin-bottom: 25px" />
            <button type="submit" id="submit_login">Sign In</button>

		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Welcome Back!</h1>
				<p>To keep connected with me please login with your personal info</p>
				<button class="ghost" id="signIn">Sign In</button>
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Hello, Friend!</h1>
				<p>Don't have an account?
                    <br>
                    Just enter your personal details and start journey with me</p>
                <button class="ghost" id="signUp">Sign Up</button>
			</div>
		</div>
	</div>
</div>

{% endblock %}


{% block scripts %}
<script src="{% static 'js/login_signup.js' %}"></script>
{% endblock %}

story9/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Logout{% endblock %}

{% block styles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/logout.css' %}">

{% endblock %}

{% block content %}

<div class="form-logout">
    <h1>Logout</h1>
    <p>Are you sure you want to log out?</p>

    <div class="button-logout" style="text-align: center; margin: 0 auto;">
        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-secondary" type="submit" name="logout" id="logout"
            style="background-color: #CA9E7B; font-family: Poppins-Light;">Yes</button>
        </form> 
        <button class="btn btn-secondary" type="submit" name="cancel" id="cancel" onclick="goBack()"
        style="background-color: #CA9E7B; font-family: Poppins-Light">Cancel</button>
    </div>
    
    
</div>
    
{% endblock %}

{% block scripts %}
<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock %}

story9/templates/registered.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login and Sign Up{% endblock %}

{% block styles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/login_signup.css' %}">

{% endblock %}

{% block content %}

<div class="container" id="container">
	<div class="form-container sign-in-container">
		<form method="POST" action="#">
            {% csrf_token %}
            
            <h1>Sign in</h1>
            <input type="text" name="username" id="username" placeholder="Username" style="margin-top: 35px" />
			<input type="password" name="password" id="password" placeholder="Password" style="margin-bottom: 25px" />
            <button type="submit">Sign In</button>

		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-right">
				<h1>Thank you for registering!</h1>
				<p>Enter your personal details and start journey with us</p>
			</div>
		</div>
	</div>
</div>

{% endblock %}


{% block scripts %}
<script src="{% static 'js/login_signup.js' %}"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 

        <title>{% block title %}{% endblock %}</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        {% block styles %}{% endblock %}
    </head>

    <body>        
            <nav class="navbar navbar-expand-md navbar-light fixed-top justifiy-content-end"
            style="background: rgba(240, 227, 219, 0.65);
            box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
            font-family: Averia Regular;
            font-size: 22px;">
            <div class="container-fluid">
                <div class="navbar-nav mr-auto">
                    <button id="theme" class="btn btn-secondary" type="button" style="background-color: #CB9A7C; margin-left: 10px">Change Theme</button> 
                </div>
                
                <button type="button" class="navbar-toggler navbar-nav ml-auto" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse text-center" id="navbarCollapse">
                        <div class="nav navbar-nav mx-auto">
                            <a href="{% url 'story7:profile' %}" class="nav-item nav-link" style="color: #454416;">home</a>
                            <a href="{% url 'story6:index' %}" class="nav-item nav-link" style="color: #454416">status</a>
                            <a href="{% url 'story8:books' %}" class="nav-item nav-link" style="color: #454416">books</a>
                        </div>

                        <div class="navbar-nav ml-auto">
                            {% if user.is_authenticated %}
                                <p style="font-size: 18px; text-align: center; margin: 10px 20px; color: #454416">Welcome, {{ user.first_name }} {{ user.last_name }}! 👋</p>
                                <button id="logout" class="btn btn-secondary" type="button" style="background-color: #CB9A7C; margin-left: 10px">
                                    <a href="{% url 'story9:logoutView' %}" style="text-decoration: none; color: white">Logout</a>
                                </button>
            
                            {% else %}
                                <p style="font-size: 18px; text-align: center; margin: 10px 20px; color: #454416">Welcome, User! 👋</p>
                                <button id="login" class="btn btn-secondary" type="button" style="background-color: #CB9A7C; margin-left: 10px">
                                    <a href="{% url 'story9:loginView' %}" style="text-decoration: none; color: white">Login</a>
                                </button>
                                
                            {% endif %}
                            
                        </div>   

                            
                </div>

                
                
                
                    
               
            </div>    
            </nav>
    

        {% block content %} {% endblock %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
        {% block scripts %}{% endblock %}
    </body>
</html>